//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarsFramework.Config {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Path {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Path() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarsFramework.Config.Path", typeof(Path).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name=&apos;isActive&apos; and @value=&apos;true&apos;].
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[@name=&apos;categoryId&apos;].
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //textarea[@name=&apos;description&apos;].
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name=&apos;endDate&apos;].
        /// </summary>
        internal static string Enddate {
            get {
                return ResourceManager.GetString("Enddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name=&apos;serviceType&apos; and @value=&apos;0&apos;].
        /// </summary>
        internal static string HourlyBasisService {
            get {
                return ResourceManager.GetString("HourlyBasisService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name=&apos;StartTime&apos; and @index=&apos;1&apos;].
        /// </summary>
        internal static string MonStartime {
            get {
                return ResourceManager.GetString("MonStartime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@value=&apos;1&apos;].
        /// </summary>
        internal static string OneOffService {
            get {
                return ResourceManager.GetString("OneOffService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name=&apos;locationType&apos; and @value=&apos;1&apos;].
        /// </summary>
        internal static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name=&apos;locationType&apos; and @value=&apos;0&apos;].
        /// </summary>
        internal static string OnSite {
            get {
                return ResourceManager.GetString("OnSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@type=&apos;button&apos; and @value=&apos;Save&apos;].
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //a[@class=&apos;ui basic green button&apos;].
        /// </summary>
        internal static string shareskill {
            get {
                return ResourceManager.GetString("shareskill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;service-listing-section&quot;]/div[2]/div/form/div[8]/div[4]/div/div/div/div/div/input.
        /// </summary>
        internal static string SkillExange {
            get {
                return ResourceManager.GetString("SkillExange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;service-listing-section&quot;]/div[2]/div/form/div[8]/div[4]/div[1]/div/div/div/div/input.
        /// </summary>
        internal static string Skillexchange1 {
            get {
                return ResourceManager.GetString("Skillexchange1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name=&apos;skillTrades&apos; and @value=&apos;true&apos;].
        /// </summary>
        internal static string Skilltrade {
            get {
                return ResourceManager.GetString("Skilltrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //select[@name=&apos;subcategoryId&apos;].
        /// </summary>
        internal static string Subcategory {
            get {
                return ResourceManager.GetString("Subcategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@placeholder=&apos;End time&apos; and @index=&apos;0&apos;].
        /// </summary>
        internal static string SunEndtime {
            get {
                return ResourceManager.GetString("SunEndtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name=&apos;StartTime&apos; and @index=&apos;0&apos;].
        /// </summary>
        internal static string SunStarttime {
            get {
                return ResourceManager.GetString("SunStarttime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /html[1]/body[1]/div[1]/div[1]/div[1]/div[2]/div[1]/form[1]/div[4]/div[2]/div[1]/div[1]/div[1]/div[1]/input[1].
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //*[@id=&quot;service-listing-section&quot;]/div[2]/div/form/div[4]/div[2]/div[1]/div/div/div/input.
        /// </summary>
        internal static string Tags1 {
            get {
                return ResourceManager.GetString("Tags1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //input[@name=&apos;title&apos;].
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
